# Generated by Django 4.2.16 on 2025-05-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(help_text='ISBN number', max_length=20, unique=True)),
                ('cover', models.URLField(blank=True, help_text='URL for the book cover image', max_length=1024, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_date', models.DateField(blank=True, help_text='Publication date', null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('author_info', models.TextField(blank=True, null=True)),
                ('author_photo', models.URLField(blank=True, help_text="URL for the author's photo", max_length=1024, null=True)),
                ('customer_review_rank', models.IntegerField(blank=True, help_text='Customer review rank or rating', null=True)),
                ('subTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
