# Generated by Django 4.2.16 on 2025-05-27 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_openending'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenEndingLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open_ending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='books.openending')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenEndingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open_ending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.openending')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='openendinglike',
            constraint=models.UniqueConstraint(fields=('user', 'open_ending'), name='unique_open_ending_like'),
        ),
    ]
