# Generated by Django 4.2.16 on 2025-05-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_openendinglike_openendingcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_source', to='books.book')),
                ('recommended_books', models.ManyToManyField(related_name='recommended_to', to='books.book')),
            ],
        ),
    ]
